# Generated by Django 6.0.2 on 2026-04-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_date', models.DateField(help_text='Last date for students to complete payment.')),
                ('message', models.TextField(default='Please complete your payment before the deadline to avoid account suspension.', help_text='Message shown to students about this deadline.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one deadline should be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
