# Generated by Django 6.0.2 on 2026-04-01 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video link (optional if video file is uploaded)', null=True),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3', null=True, upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])]),
        ),
    ]
