# Generated by Django 6.0.2 on 2026-03-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('Matric', 'Matric'), ('Intermediate', 'Intermediate')], max_length=25, null=True),
        ),
    ]
