# Generated by Django 6.0.2 on 2026-04-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.BooleanField(default=False, help_text='Check to grant student full access to all features after payment is confirmed.'),
        ),
    ]
