# Generated by Django 6.0.2 on 2026-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_expiry_date',
            field=models.DateField(blank=True, help_text="Date when the student's access expires. Leave blank for unlimited.", null=True),
        ),
    ]
